"""
Configuration loader for VectorMerge.

This module provides functionality to load configuration from multiple sources
with proper precedence: CLI args > project config > global config > defaults.
"""

import os
import yaml
from pathlib import Path
from typing import Dict, Any, Optional, Union
from dataclasses import dataclass, field
from ..mapping.base import MappingConfig
from ..clustering.base import ClusteringConfig
from ruamel.yaml import YAML
from ruamel.yaml.comments import CommentedMap
import io

import dataclasses
from typing import Any, Dict

copyright_info = """
Copyright (c) 2025, VectorMerge
All rights reserved.

This software is provided "as is" without warranty of any kind, express or implied, including but not limited to the warranties of merchantability, fitness for a particular purpose and noninfringement. In no event shall the authors or copyright holders be liable for any claim, damages or other liability, whether in an action of contract, tort or otherwise, arising from, out of or in connection with the software or the use or other dealings in the software.

## Notice:
You can edit this file to change the configuration of VectorMerge.

The configuration is stored in the following files (will be loaded in order of precedence):
- $VECTORMERGE_PACKAGE_PATH/configs/config.yaml (package config)
- ~/.vectormerge/config.yaml (global config)
- ./.vectormerge/config.yaml (local config)

🎉🎉This file is generated by VectorMerge
============================ VectorMerge Config ============================
"""


def _to_dict_recursive(obj: Any) -> Any:
    """
    Recursively convert a dataclass to a dictionary.

    """
    if dataclasses.is_dataclass(obj) and not isinstance(obj, type):
        result = {}
        for field in dataclasses.fields(obj):
            value = getattr(obj, field.name)
            result[field.name] = _to_dict_recursive(value)
        return result
    elif isinstance(obj, dict):
        return {key: _to_dict_recursive(value) for key, value in obj.items()}
    elif isinstance(obj, (list, tuple)):
        return [_to_dict_recursive(item) for item in obj]
    else:
        return obj


@dataclass
class VectorMergeConfig:
    """Configuration container for VectorMerge."""
    
    # Path settings
    data_path: str = "./data/raw/beir/"
    embedding_path: str = "./data/processed/embeddings/"
    reference_path: str = "./data/processed/references/"
    mapping_path: str = "./data/processed/mappings/"
    mapping_param_path: str = "./output/mapping_models/"
    mapping_embedding_path: str = "./output/mapping_embeddings/"
    cluster_path: str = "./data/processed/clusters/"

    mapping_config: MappingConfig = MappingConfig()
    clustering_config: ClusteringConfig = ClusteringConfig()
    

    def to_yaml(self) -> str:
        """Convert configuration to YAML string."""
        return yaml.dump(self.__dict__)

    def to_commented_yaml(self) -> str:
        """Convert configuration to YAML string with comments."""
        yaml = YAML()
        yaml.default_flow_style = False
        yaml.indent(mapping=2, sequence=4, offset=2)
        yaml.width = 4096
        
        config_dict = CommentedMap(self.to_dict())
        
        config_dict.yaml_set_start_comment(copyright_info)
        config_dict.yaml_set_comment_before_after_key(
            'mapping_config',
            before='============================ mapper config ============================',
            indent=0
        )
        
        config_dict.yaml_set_comment_before_after_key(
            'clustering_config', 
            before='============================ clustering config ============================',
            indent=0
        )
        
        
        stream = io.StringIO()
        yaml.dump(config_dict, stream)
        return stream.getvalue()
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert configuration to dictionary."""
        return _to_dict_recursive(self)
    

class ConfigLoader:
    """Loads configuration from multiple sources with proper precedence."""
    
    def __init__(self):
        self.config = VectorMergeConfig()
        self._cached_configs = {}
        self._load_configs()
    
    def to_commented_yaml(self) -> str:
        """Convert configuration to YAML string with comments."""
        return self.config.to_commented_yaml()
    
    @property
    def package_config_path(self) -> Path:
        """Get the path to the package config."""
        return Path(__file__).parent.parent.parent / "configs" / "config.yaml"
    
    @property
    def global_config_path(self) -> Path:
        """Get the path to the global config."""
        return Path.home() / ".vectormerge" / "config.yaml"
    
    @property
    def local_config_path(self) -> Path:
        """Get the path to the local config."""
        return Path.cwd() / ".vectormerge" / "config.yaml"
    
    def _load_configs(self):
        """Load configurations in order of precedence."""
        # Load all config sources
        configs = {
            'package': self._load_package_config(),
            'global': self._load_global_config(), 
            'project': self._load_project_config()
        }
        
        # Merge in order of precedence (package -> global -> project)
        for config_type, config_data in configs.items():
            if config_data:
                self._cached_configs[config_type] = config_data
                self._merge_config(config_data)

    def load_yaml_config(self, config_path: Path) -> Optional[Dict[str, Any]]:
        """Load configuration from YAML file."""
        return self._load_config_file(config_path)
    
    def _load_config_file(self, config_path: Path) -> Optional[Dict[str, Any]]:
        """Generic config file loader."""
        try:
            if config_path.exists():
                with open(config_path, 'r', encoding='utf-8') as f:
                    return yaml.safe_load(f)
        except Exception as e:
            print(f"Warning: Could not load config from {config_path}: {e}")
        return None
    
    def _load_package_config(self) -> Optional[Dict[str, Any]]:
        """Load config from package's configs/config.yaml."""
        package_dir = Path(__file__).parent.parent.parent
        return self._load_config_file(package_dir / "configs" / "config.yaml")
    
    def _load_global_config(self) -> Optional[Dict[str, Any]]:
        """Load config from ~/.vectormerge/config.yaml."""
        return self._load_config_file(Path.home() / ".vectormerge" / "config.yaml")
    
    def _load_project_config(self) -> Optional[Dict[str, Any]]:
        """Load config from ./.vectormerge/config.yaml."""
        return self._load_config_file(Path.cwd() / ".vectormerge" / "config.yaml")
    
    def _merge_config(self, config_dict: Dict[str, Any]):
        """Merge configuration dictionary into current config."""
        for key, value in config_dict.items():
            if hasattr(self.config, key):
                setattr(self.config, key, value)
    
    def _load_config_from_yaml(self, config_path: Path) -> Optional[Dict[str, Any]]:
        """Load configuration from YAML file."""
        if config_path.exists():
            return self._load_config_file(config_path)
        return None
    
    def get_default(self, key: str, fallback: Any = None) -> Any:
        """Get a default value from config."""
        return getattr(self.config, key, fallback)