# VectorMerge Configuration File
# This file contains default settings for VectorMerge

# ==================== Paths ====================
data_path: "./data/raw/beir/"
embedding_path: "./data/processed/embeddings/"
reference_path: "./data/processed/references/"
cluster_path: "./data/processed/clusters/"
mapping_param_path: "./output/mapping_models/"
mapping_embedding_path: "./output/mapping_embeddings/"

# ==================== Mapper Configuration ====================
mapper:
  method: "nonlinear"
  save_param: true
  save_embedding: true
  device: "auto"
  reference_key: "random_split_scifact_0.33"

mapper_method:
  nonlinear:
    num_layers: 3
    hidden_dim: 512
    learning_rate: 0.001
    batch_size: 32
    num_epochs: 100
    loss_type: "mse"

  procrustes:
    with_rotation: true
    with_scaling: true
    approximate: false
    q: 1500
    use_pca: false
    reduced_dim: 0
    procrustes_pca_type: "none"

  la2m:
    cluster_method: "la2m-cluster" # la2m-cluster, kmeans
    d_prime: 10
    save_transformed: true
    with_rotation: true
    with_scaling: true
    approximate: false
    q: 1500
    use_pca: false
    reduced_dim: 0
    procrustes_pca_type: "none"

# ==================== Cluster Configuration ====================
cluster:
  method: "la2m-cluster"
  reference_key: "random_split_scifact_0.33"

cluster_method:
  la2m-cluster:
    num_clusters: 50
    d_prime: 10
  kmeans:
    num_clusters: 50

# ==================== Embedding Models Configuration ====================
embedding_models:
  mistral:
    model_name: mistral-embed
    batch_size: 32
    device: cpu
    max_tokens: 8192
    sleep_time: 2

  openai:
    model_name: text-embedding-3-small
    batch_size: 16
    device: cpu
    
  nv-embed:
    model_name: nv-embed
    batch_size: 32
    device: cuda
    model_path: "~/.cache/embedding_models/nv-embed/"
    max_tokens: 8192
    
  gte:
    model_name: Alibaba-NLP/gte-Qwen2-7B-instruct
    batch_size: 32
    device: cuda
    model_path: "~/.cache/embedding_models/gte/"
    max_tokens: 8192
    
  fast-text:
    model_name: fast-text
    batch_size: 64
    device: cpu
    model_path: "~/.cache/embedding_models/fast-text/"
    
  word2vec:
    model_name: word2vec
    batch_size: 64
    device: cpu
    
  glove:
    model_name: glove
    batch_size: 64
    device: cpu
    dim: 300
    model_path: "~/.cache/embedding_models/glove.6B/"

# ======================================================
